preserve_hierarchy: 1
files:
  - source: /website/src/pages/en/**/*.mdx
    translation: /website/src/pages/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
    content_segmentation: 0
  - source: /website/src/pages/en/**/*.md
    translation: /website/src/pages/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
    content_segmentation: 0
  - source: /website/src/pages/en/**/*.json
    translation: /website/src/pages/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
    content_segmentation: 0
