files:
  - source: /pages/en/**/*.mdx
    translation: /pages/%two_letters_code%/**/%original_file_name%
    content_segmentation: 0
    update_option: update_as_unapproved
  - source: /pages/en/**/*.json
    translation: /pages/%two_letters_code%/**/%original_file_name%
    content_segmentation: 0
    update_option: update_as_unapproved
