preserve_hierarchy: 1
files:
  - source: /website/pages/en/**/*.mdx
    ignore:
      - '/website/pages/en/**/\[\[...slug\]\].mdx'
    translation: /website/pages/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
  - source: /website/pages/en/**/*.json
    translation: /website/pages/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
    content_segmentation: 0
