preserve_hierarchy: true
files:
  - source: /pages/en/**/*.mdx
    translation: /pages/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
    content_segmentation: 0
  - source: /pages/en/**/*.json
    translation: /pages/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
    content_segmentation: 0
