export default {
  'subgraph-composition': '',
  'subgraph-debug-forking': '',
  near: '',
  grafting: '',
  'subgraph-linter': '',
  'subgraph-uncrashable': '',
  'transfer-to-the-graph': '',
  enums: '',
  'secure-api-keys-nextjs': '',
  polymarket: '',
  agent0: '',
  'x402-payments': '',
  'contract-analyzer': '',
}
