---
title: Using a Multisig Wallet
---

Subgraph Studio currently doesn't support signing with multisig wallets. Until then, you can follow this guide on how to publish your subgraph by invoking the [GNS contract](https://github.com/graphprotocol/contracts/blob/dev/contracts/discovery/GNS.sol) functions.

### Create a Subgraph

Similarly to using a regular wallet, you can create a subgraph by connecting your non-multisig wallet in Subgraph Studio. Once you connect the wallet, simply create a new subgraph. Make sure you fill out all the details, such as subgraph name, description, image, website, and source code URL if applicable.

For initializing a starter subgraph, you can follow the commands shown in the UI, or simply run

```
graph init --studio <SUBGRAPH_SLUG>
```

`SUBGRAPH_SLUG` is the name of your subgraph that you can copy from the UI or the URL in the browser. This command should create a folder in your file system with all the necessary files to start developing a subgraph.

### Deploy a Subgraph

Once your subgraph is ready to be deployed to the graph node, simply follow the commands shown in the UI, or run the following command:

```
graph deploy --studio <SUBGRAPH_SLUG>
```

**Note**: Make sure that you are inside the subgraph folder before running the command.

### Publish a Subgraph or a Version

You can either publish a new subgraph to the decentralized network or publish a new version of the previously published subgraph.

#### Publish a New Subgraph

There are a couple of ways to publish a subgraph using multisig wallets. Here we'll describe invoking the [`publishNewSubgraph`](https://github.com/graphprotocol/contracts/blob/dev/contracts/discovery/GNS.sol#L231) function in the [GNS contract](https://etherscan.io/address/0xaDcA0dd4729c8BA3aCf3E99F3A9f471EF37b6825) using Etherscan.

Before we use that function, we need to generate input arguments for it. Access [this page](https://thegraph.com/studio/multisig) in Subgraph Studio and provide the following:

- Ethereum address of your multisig wallet
- Subgraph that you want to publish
- Version that you want to publish

After clicking on "Get Arguments", we'll generate all the contract arguments for you!

There should be 4 arguments:

- `graphAccount`: which is your multisig account address
- `subgraphDeploymentID`: the hex hash of the deployment ID for that subgraph
- `versionMetadata`: version metadata (label and description) that gets uploaded to IPFS. The hex hash value for that JSON file will be provided.
- `subgraphMetadata`: similar to version metadata, subgraph metadata (name, image, description, website, and source code URL) gets uploaded to IPFS, and we provide the hex hash value for that JSON file

With those 4 arguments, you should be able to:

- Visit [our GraphProxy](https://etherscan.io/address/0xaDcA0dd4729c8BA3aCf3E99F3A9f471EF37b6825#writeProxyContract) contract on Etherscan
- Connect to Etherscan using WalletConnect via the WalletConnect Safe app of your multisig
- Call the `publishNewSubgraph` method with the parameters that were generated by our tool

#### Publish a New Version

To publish a new version of an existing subgraph we first need to generate input arguments for it. Access [this page](https://thegraph.com/studio/multisig) in Subgraph Studio and provide:

- Ethereum address of your multisig wallet
- Subgraph that you want to publish
- Version that you want to publish
- The ID of the subgraph you want to update in Graph Explorer

After clicking on "Get Arguments" we'll generate all the contract arguments for you!

On the right side of the UI under the `Publish New Version` title, there should be 4 arguments:

- `graphAccount`: which is your Multisig account address
- `subgraphNumber`: is the number of your already published subgraph. It is a part of the subgraph id for a published subgraph queried through The Graph Network subgraph.
- `subgraphDeploymentID`: which is the hex hash of the deployment ID for that subgraph
- `versionMetadata`: version metadata (label and description) gets uploaded to IPFS, and we provide the hex hash value for that JSON file

Now that we generated all the arguments you are ready to proceed and call the `publishNewVersion` method. To do so, you should:

- Visit [the GraphProxy](https://etherscan.io/address/0xaDcA0dd4729c8BA3aCf3E99F3A9f471EF37b6825#writeProxyContract) contract on Etherscan
- Connect to Etherscan using WalletConnect via the WalletConnect Safe app of your Multisig
- Call the `publishNewVersion` method with the parameters that were generated by our tool

Once the transaction is successful, your subgraph should have a new version of your subgraph in Graph Explorer which means that curators can start signaling on it and indexers can start indexing it.
