export default {
  'subgraph-debug-forking': '',
  near: '',
  arweave: '',
  grafting: '',
  'subgraph-uncrashable': '',
  'transfer-to-the-graph': '',
  pruning: '',
  derivedfrom: '',
  'immutable-entities-bytes-as-ids': '',
  'avoid-eth-calls': '',
  timeseries: '',
  'grafting-hotfix': '',
  enums: '',
  'secure-api-keys-nextjs': '',
  polymarket: '',
}
