export default {
  'base-testnet': '',
  'upgrading-a-subgraph': '',
  'subgraph-debug-forking': '',
  near: '',
  cosmos: '',
  arweave: '',
  grafting: '',
  'subgraph-uncrashable': '',
  'substreams-powered-subgraphs': '',
  'subgraph-best-practice-1': 'Subgraph Best Practice 1: Pruning with indexerHints',
  'subgraph-best-practice-2': 'Subgraph Best Practice 2: Manage Arrays with @derivedFrom',
  'subgraph-best-practice-3': 'Subgraph Best Practice 3: Using Immutable Entities and Bytes as IDs',
  'subgraph-best-practice-4': 'Subgraph Best Practice 4: Avoid eth_calls',
}
