export default {
  'base-testnet': '',
  'upgrading-a-subgraph': '',
  'subgraph-debug-forking': '',
  near: '',
  cosmos: '',
  arweave: '',
  grafting: '',
  'subgraph-uncrashable': '',
  'substreams-powered-subgraphs': '',
  pruning: '',
  derivedfrom: '',
  'immutable-entities-bytes-as-ids': '',
  'avoid-eth-calls': '',
}
