export default {
  'base-testnet': '',
  'upgrading-a-subgraph': '',
  'subgraph-debug-forking': '',
  near: '',
  cosmos: '',
  arweave: '',
  grafting: '',
  'subgraph-uncrashable': '',
  'substreams-powered-subgraphs': '',
  pruning: 'Subgraph Best Practice 1: Pruning with indexerHints',
  derivedFrom: 'Subgraph Best Practice 2: Manage Arrays with @derivedFrom',
  'immutable-entities-bytes-as-ids': 'Subgraph Best Practice 3: Using Immutable Entities and Bytes as IDs',
  'avoid-eth-calls': 'Subgraph Best Practice 4: Avoid eth_calls',
}
