export default {
  index: '',
  about: '',
  'supported-networks': '',
  overview: 'Overview',
  '---1': {
    type: 'separator',
  },
  '###1': {
    type: 'heading',
    title: 'Products',
  },
  substreams: '',
  sps: 'Substreams-powered Subgraphs',
  '---2': {
    type: 'separator',
  },
  '###2': {
    type: 'heading',
    title: 'Subgraphs',
  },
  'quick-start': '',
  explorer: '',
  querying: 'Querying',
  developing: 'Developing',
  deploying: 'Deploying',
  publishing: 'Publishing',
  curating: '',
  managing: 'Managing',
  billing: '',
  benefits: 'Benefits',
  cookbook: 'Cookbooks',
  'release-notes': 'Release Notes & Upgrade Guides',
  '---3': {
    type: 'separator',
  },
  '###3': {
    type: 'heading',
    title: 'Substreams',
  },
  substreams: '',
  sps: 'Substreams-powered Subgraphs',
  '---4': {
    type: 'separator',
  },
  '###4': {
    type: 'heading',
    title: 'Indexing',
  },
  indexing: '',
  'operating-graph-node': '',
  tap: '',
  'chain-integration-overview': '',
  'supported-network-requirements': '',
  'new-chain-integration': '',
  firehose: '',
  graphcast: '',
  '---5': {
    type: 'separator',
  },
  '###5': {
    type: 'heading',
    title: 'Delegators',
  },
  delegating: '',
  '---6': {
    type: 'separator',
  },
  '###6': {
    type: 'heading',
    title: 'Resources',
  },
  tokenomics: 'Tokenomics',
  contracts: 'Contracts',
  glossary: '',
  '---7': {
    type: 'separator',
  },
  '###7': {
    type: 'heading',
    title: 'Archived',
  },
  sunrise: 'Post-Sunrise Upgrade FAQ',
  arbitrum: 'Scaling with Arbitrum',
}
