export default {
  index: '',
  '---1': {
    type: 'separator',
  },
  '###1': {
    type: 'heading',
    title: 'Overview',
  },
  about: '',
  network: 'The Graph Network',
  tokenomics: 'Tokenomics',
  contracts: 'Protocol Contracts',
  glossary: '',
  explorer: '',
  firehose: '',
  substreams: '',
  '---2': {
    type: 'separator',
  },
  '###2': {
    type: 'heading',
    title: 'Developers',
  },
  'quick-start': '',
  developing: 'Developing',
  deploying: 'Deploying',
  publishing: 'Publishing',
  managing: 'Managing',
  querying: 'Querying',
  cookbook: 'Cookbook',
  'release-notes': 'Release Notes & Upgrade Guides',
  '---3': {
    type: 'separator',
  },
  '###3': {
    type: 'heading',
    title: 'Indexers',
  },
  'operating-graph-node': '',
  'chain-integration-overview': '',
  'supported-network-requirements': '',
  'new-chain-integration': '',
  graphcast: '',
  '---4': {
    type: 'separator',
  },
  '###4': {
    type: 'heading',
    title: 'Archived',
  },
  sunrise: 'Post-Sunrise Upgrade FAQ',
  'mips-faqs': '',
  arbitrum: 'Scaling with Arbitrum',
}
