export default {
  index: '',
  '---1': {
    type: 'separator',
  },
  about: '',
  network: 'The Graph Network',
  sunrise: 'Post-Sunrise Upgrade FAQ',
  billing: '',
  glossary: '',
  tokenomics: 'Tokenomics',
  arbitrum: 'Scaling with Arbitrum',
  '---2': {
    type: 'separator',
  },
  '###1': {
    type: 'heading',
    title: 'Subgraphs',
  },
  'quick-start': '',
  developing: 'Developing',
  deploying: 'Deploying',
  publishing: 'Publishing',
  managing: 'Managing',
  querying: 'Querying',
  cookbook: 'Cookbook',
  'release-notes': 'Release Notes & Upgrade Guides',
  '---3': {
    type: 'separator',
  },
  '###2': {
    type: 'heading',
    title: 'Substreams',
  },
  substreams: '',
  '---4': {
    type: 'separator',
  },
  '###3': {
    type: 'heading',
    title: 'Indexing',
  },
  'operating-graph-node': '',
  tap: '',
  'chain-integration-overview': '',
  'supported-network-requirements': '',
  'new-chain-integration': '',
  firehose: '',
  graphcast: '',
  'mips-faqs': '',
}
