apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graph-docs
  annotations:
    cert-manager.io/issuer: 'prod-cluster-origin-issuer'
    cert-manager.io/issuer-kind: 'ClusterOriginIssuer'
    cert-manager.io/issuer-group: 'cert-manager.k8s.cloudflare.com'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - thegraph.com
      secretName: thegraph-com-tls
  rules:
    - host: thegraph.com
      http:
        paths:
          - backend:
              service:
                name: graph-docs
                port:
                  name: http
            path: /docs
            pathType: Prefix
