name: Pull Request CI/CD TEST

on:
  push:
    branches:
      - martynas/pull-request-cicd-fix

env:
  BASE_IMAGE: ghcr.io/graphprotocol/graph-docs-staging
  NEXT_PUBLIC_BASE_PATH: /docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # required to respect .dockerignore
          cache-from: type=registry,ref=${{ env.BASE_IMAGE }}:latest
          secrets: npmrc=//registry.npmjs.org/:_authToken=${{ secrets.NPM_SECRET_TOKEN }}
          push: false
