name: Pull Request CI/CD TEST

on:
  push:
    branches:
      - martynas/pull-request-cicd-fix

env:
  NEXT_PUBLIC_BASE_PATH: /docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # required to respect .dockerignore
          push: false
