name: OpenGraph Service

on:
  push:
    branches: [main]
    paths:
      - 'packages/og-image/**'

  workflow_dispatch:
    inputs:
      commit:
        required: false
        description: 'Commit ID'

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.COMMIT }}

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: Deploy
        working-directory: ./packages/og-image
        run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.GUILD_CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.GUILD_CF_ACCOUNT_ID }}
